language: python

python:
  - 2.7
  - 3.5
  - pypy

sudo: false

install:
  - pip install coverage coveralls  # coverage testing
  - pip install .

# Run test
script: nosetests --with-coverage --cover-package=pilight

after_success:
- coveralls